services:
  redis:
    image: redis:7.0-alpine
    container_name: rate-limiter-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiter-app
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    # Caso queira ver os logs no terminal:
    # command: ["/app/server"]